### ISSUE TITLE
Resolve chat parser error that occurs occasionally

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/Points-Thing#18]
```
com.glide.script.RhinoEcmaError: The undefined value has no properties.
sys_script.692ca881dba29150791d8f8d139619ee.script : Line(5) column(0)
2:
3: var message = JSON.parse(current.payload);
4:
==> 5: var userSlackID = message.event.user.replace(/<@/g,"").replace(/>/g,"");
6: var userSysID = new x_snc_pointsthing.PointsThing().establish_user(userSlackID, false);
7:
8: if (!message.event.text || !userSysID) return;
```

unsure of what is causing it

**Comment by SapphicFire** [comment]
Hey Earl,

I haven't been able to generate a message that doesn't have the .user or (unlikely) the .event object, would you be able to search for
`sys_created_onONToday@javascript:gs.beginningOfToday()@javascript:gs.endOfToday()^payloadNOT LIKE"user":`
on the payload table and give us some examples I can work with, if that's OK? We can test for the missing attribute easily enough, but being able to assess the model would make sure we can have a more permanent solution validated.

**Comment by SapphicFire** [comment]
Ok, found it. Slack has a couple of message payload formats that won't have the user property directly within the event object. The most likely trigger is message_changed (people updating their messages).

### Reason for error 🔍:

The payloads that don't work have the subtype property under event, and only the following subtypes change format:

- "message_changed"
- "message_replied" - This is currently bugged and doesn't get formatted as expected, but something to keep in mind for future - [message_replied documentation](https://api.slack.com/events/message/message_replied)

### Proposed fix 🛠️:

Test for the user or subtype property and if present, test the subtype and change where you draw slackID from respectively

#### Code snippet:
```js
var userSlackID, message = JSON.parse(current.payload);
if (current.event.hasOwnProperty('subtype') && (current.event.subtype === "message_changed" /* || current.event.subtype === "message_replied" */)) {
	userSlackID = message.event.message.user.replace(/<@/g,"").replace(/>/g,"");
}
userSlackID = message.event.user.replace(/<@/g,"").replace(/>/g,"");
```

### Conversation 🗣️:

Implementing that would mean we would support points on edit, which could add a chance to be gamed (although we could report on that, or set limits). 

Alternatively we could add checks for it, and then return without inserting the chats so we avoid the error and triggering actions off the chats. Would be interested for input on preferences for how we implement that?

**Comment by earlduque** [comment]
Thanks @SapphicFire for the findings, thank you for figuring it out. I added a an ignore on the scripted rest api, the payload is no longer created on `message_changed` events

```javascript
if (request.body.data.event.bot_id || request.body.data.event.subtype == 'message_changed') return;
```

**Comment by chelming** [comment]
:ohno: this will break trebek not firing multiple times because that was relying on the message_changed from the event unfurling.

**Comment by chelming** [comment]
but... that was a hack anyway 😄 

I think we should store/process `request.body.data.event.bot_id` so we can see if/when the bot last posted a message but that'd require updates to basically ignore them in all other instances.

perhaps adding a `u_is_bot` on the user record and not firing if the message was from a bot?

**Comment by SapphicFire** [comment]
This shouldn't have any bearing on trebek since we're talking PointsThing not Slacker 😜

**Comment by earlduque** [comment]
you got TOLD @chelming 🔥

**Comment by chelming** [comment]
nothing_to_see_here.gif
