### ISSUE TITLE
Create API so that points can come from other scopes or external APIs

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/Points-Thing#2]

**Comment by SapphicFire** [comment]
Hey Earl, would you mind expanding on what your vision with this is? Happy to take a swing at it but keen to understand use cases and validations you have in mind

**Comment by earlduque** [comment]
If you see in the existing app, I created a API point table, this was meant to be alongside the chat table and this app would accept points from two different locations, but essentially use the same script include for processing the points.

I wanted to make a for-internal-use script include to create records on this table that would then activate the points incrementing and also create a scripted REST api for receiving points from external systems.

I'll expand more as needed or as I think of it.
