### ISSUE TITLE
Friday Fun leader emoji replacement

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/Points-Thing#21]
![image](https://user-images.githubusercontent.com/31702109/197247824-d20d5225-eb93-4db7-9e17-56d1107eebcf.png)

additional requirements:
- new property that turns on or off this feature, default to false
- this must only happen on !leaderboard calls, so must only do the replacement if second parameter of the leaderboard call is true

**Comment by earlduque** [comment]
I don't think I committed the last change lol I'll check later, thanks for letting me know

**Comment by eriemer1** [comment]
This was done with or #26
