### ISSUE TITLE
Spell "lofty" correctly 😂

### ISSUE THREAD

**Issue by chelming** [ServiceNowDevProgram/Points-Thing#30]
>Not many have acsended to this lofy height, but Chris Helming just scored :1000: total points! (1000 total) :first_place_medal:

**Comment by wiz0floyd** [comment]
Not a bad idea to have a spell check pass on the whole app. If whoever takes this is feeling extra ambitious make all of the messages translatable too.

**Comment by DavidMarcial** [comment]
I will try to tackle this one, idk about the translatable part though
